---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: hello-stateful
  name: joatmon08-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeName: joatmon08-pv
