---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: joatmon08-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://{{ AWS region }}/{{ volume ID }}
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
