---
apiVersion: v1
kind: Service
metadata:
  name: hello-stateful
  labels:
    app: hello-stateful
spec:
  clusterIP: None
  selector:
    app: hello-stateful
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello-stateful
spec:
  selector:
    matchLabels:
      app: hello-stateful
  serviceName: hello-stateful
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-stateful
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: hello-stateful
        image: joatmon08/hello-stateful:1.0
        volumeMounts:
        - name: log
          mountPath: /usr/share/hello
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: joatmon08-pvc