---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <match fluent.**>
      @type null
    </match>

    <source>
      @type tail
      path "/var/log/containers/*.log"
      pos_file /var/log/containers/logz-pos-containers.log.pos
      exclude_path ["/var/log/containers/*.log.pos"]
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      keep_time_key true
      tag kubernetes.*
      format json
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <match kubernetes.var.log.containers.**_default_fluentd-**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**_kube-system_**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**_istio-system_**.log>
      @type null
    </match>

    <match kubernetes.**>
      @type stdout
    </match>
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fluentd
  template:
    metadata:
      labels:
        run: fluentd
    spec:
      containers:
      - name: fluentd
        image: fabric8/fluentd-kubernetes
        volumeMounts:
        - name: config-volume
          mountPath: /etc/fluent/
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers