---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: www-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-f2617ebf-3e0b-11e8-b2b3-080027732cee